### ISSUE TITLE
SOLVED Segmentation Fault

### ISSUE THREAD

**Issue by stevenls25** [linux4sam/egt#13]
When running your dialogs program, It compiles ok and starts ok, I see all the buttons,
but the File Open and Message Dialog buttons give me a Segmentation fault on my board 
(with SAMA5D27 SOM1).  The other three buttons seem to work properly.

![Screenshot from 2021-03-05 10-13-05](https://user-images.githubusercontent.com/80113699/110134769-c137e200-7d9b-11eb-86d3-35349f9c589e.png)

**Comment by SandeepSM** [comment]
Hi,
   I am not able to reproduce segmentation fault you observed from out egt_dialog application. can you be more specific or the steps to reproduce this issue. if possible can you share your code snippet of dialog_box_demo ?

Regards,
Sandeep Sheriker M

**Comment by stevenls25** [comment]
Was hardware issue not software.
Thank You
