### ISSUE TITLE
EGT progress bar can't be shown

### ISSUE THREAD

**Issue by NelsonKon** [linux4sam/egt#14]
Hi,
Is there any example of how to show out the progress of a process using progressbar?

I tried to do this

adcch6_btn->on_click([adcch6_progress](egt::Event&)
{
    adcch6_progress->show();
    ret = iio_adc_settings();

});

My progress bar just doesn't appear.  I need to comment out ret = iio_adc_settings();, then only it'll appear.

Does it have to do with event?
Looks like the UI thread is stuck
For Visual C++, we can use application.doevent().  But is there similar function in EGT?

**Comment by ldesroches** [comment]
Hi Nelson,

Please stop use issues as a way to request help about how to use EGT and general topics as C++ and Linux. We want to keep this channel for bugs. When it comes about using EGT, please use the EGT forum: https://www.microchip.com/forums/f551.aspx.

I am aware you have some troubles with the forum. Let see if we can fix this.

Regards
