### ISSUE TITLE
Scrolledview imagebutton example

### ISSUE THREAD

**Issue by swsuh66** [linux4sam/egt#15]
Dear ldesroches,

I built and test imagebutton.cpp
When pressing the button after scrolling acts as if the button in another area was pressed.
It seens butten event have some error.

Thanks
Regards
Brian

**Comment by ldesroches** [comment]
Hello Brian,

Thanks for the report. The goal of the example was to display different layouts, but it's true that pressing buttons doesn't work when we move into the window, there is an offset. This is probably a bug in the ScrolledView. I'll have a look.

Regards,
Ludovic

**Comment by ldesroches** [comment]
Fix pushed. Let me know if you still have bugs.

Regards,
Ludovic
