### ISSUE TITLE
ScrolledView issue

### ISSUE THREAD

**Issue by OhYoungJin1** [linux4sam/egt#21]
Scroller background not transparent in ScrolledView

I found 

[view.cpp 102]
To prevent this situation, we force the background drawing of the ScrolledView even if fill flags are set to none.

please...

**Comment by ldesroches** [comment]
Hi,

Sorry I don't get the issue. You have an issue with the horizontal and vertical scrollers?
![Screenshot from 2022-05-10 15-08-40](https://user-images.githubusercontent.com/995766/167635901-2e074a06-f33c-4907-b435-d3f9013cb3da.png)
Is something wrong with this?

Can you share a picture of what is not behaving as you expect?

Regards,
Ludovic

**Comment by OhYoungJin1** [comment]
![1](https://user-images.githubusercontent.com/105038333/168506659-835f0a5e-2020-4c3c-9ed3-1ad043a441f6.png)

I want the gray area to be transparent

ex)
auto list = make_shared<egt::ScrolledView>(ScrolledView::Policy::as_needed, ScrolledView::Policy::as_needed);
list->fill_flags(Theme::FillFlag::blend);
list->color(Palette::ColorId::bg, Palette::transparent);
-----> 
![22](https://user-images.githubusercontent.com/105038333/168506148-d8b5d77e-471e-405c-b986-4a7a133eca08.png)


auto list = make_shared<egt::ScrolledView>(ScrolledView::Policy::as_needed, ScrolledView::Policy::as_needed);
list->fill_flags(Theme::FillFlag::blend);
list->color(Palette::ColorId::bg, egt::Color(229, 229, 229));
-----> 
![33](https://user-images.githubusercontent.com/105038333/168506320-789096fa-0d26-4070-9282-96715ba83da0.png)




list->color(Palette::ColorId::bg, Palette::transparent);  --> background color is black!
list->color(Palette::ColorId::bg, egt::Color(229, 229, 229));  --> background color is gray!

**Comment by OhYoungJin1** [comment]
![1](https://user-images.githubusercontent.com/105038333/168506659-835f0a5e-2020-4c3c-9ed3-1ad043a441f6.png)

I want the gray area to be transparent

ex)
auto list = make_shared<egt::ScrolledView>(ScrolledView::Policy::as_needed, ScrolledView::Policy::as_needed);
list->fill_flags(Theme::FillFlag::blend);
list->color(Palette::ColorId::bg, Palette::transparent);
-----> 
![22](https://user-images.githubusercontent.com/105038333/168506148-d8b5d77e-471e-405c-b986-4a7a133eca08.png)


auto list = make_shared<egt::ScrolledView>(ScrolledView::Policy::as_needed, ScrolledView::Policy::as_needed);
list->fill_flags(Theme::FillFlag::blend);
list->color(Palette::ColorId::bg, egt::Color(229, 229, 229));
-----> 
![33](https://user-images.githubusercontent.com/105038333/168506320-789096fa-0d26-4070-9282-96715ba83da0.png)




list->color(Palette::ColorId::bg, Palette::transparent);  --> background color is black!
list->color(Palette::ColorId::bg, egt::Color(229, 229, 229));  --> background color is gray!

**Comment by ldesroches** [comment]
The issue is probably related to the widgets inside your ScrolledView

egt::TopWindow window;
window.color(egt::Palette::ColorId::bg, egt::Palette::blue);
egt::ScrolledView view(window, egt::Rect(0, 0, 200, 200));
egt::Frame frame(egt::Rect(egt::Point(), egt::Size(400, 400)));
frame.fill_flags(egt::Theme::FillFlag::blend);
frame.color(egt::Palette::ColorId::bg, egt::Palette::transparent);
view.add(frame);
window.show();

![image](https://user-images.githubusercontent.com/995766/171172877-3bee5edb-22c9-4f1f-bfb0-ca3fca37f717.png)

**Comment by OhYoungJin1** [comment]
The issue is probably related to the widgets inside your ScrolledView
------> Everything was resolved well !!

Thank you!!!
