### ISSUE TITLE
Blurry logo on HiDPI displays

### ISSUE THREAD

**Issue by paulmenzel** [linux4sam/egt#26]
The [logo referenced in the README](https://github.com/linux4sam/egt/raw/master/docs/src/logo.png) is blurry on HiDPI displays.

**Comment by ldesroches** [comment]
Hello,

What do you mean? On desktop machines when displaying the README or using this logo in EGT apps?

Regards,
Ludovic

**Comment by paulmenzel** [comment]
I mean when displaying the README.
